const nodes = new vis.DataSet([
    {id: 0, label: 'Faisal'}, 
    {id: 1, label: ' Zeenat'}, 
    {id: 2, label: 'A C Jesudoss Prabhakaran'}, 
    {id: 3, label: 'Abarghuei Mirazimi Faezeh'}, 
    {id: 4, label: 'Adam T Groth'}, 
    {id: 5, label: 'Akihiro Wada'}, 
    {id: 6, label: 'Akrem Jalel'}, 
    {id: 7, label: 'Alan M Krensky'}, 
    {id: 8, label: 'Amanuel Bahiru'}, 
    {id: 9, label: 'Amar Nath Mehrotra'}, 
    {id: 10, label: 'Anca Daniela Vladoi'}, 
    {id: 11, label: 'Anusuya Ramasamy'}, 
    {id: 12, label: 'Arbabian Sedigheh'}, 
    {id: 13, label: 'Arunava Kali'}, 
    {id: 14, label: 'Ashraf F I Nabhan'}, 
    {id: 15, label: 'Asri Yones'}, 
    {id: 16, label: 'Assadi Mostafa'}, 
    {id: 17, label: 'Atsuhisa Ueda'}, 
    {id: 18, label: 'Awatef Msolly'}, 
    {id: 19, label: 'Berhanu Sisay'}, 
    {id: 20, label: 'Bi Dezhong'}, 
    {id: 21, label: 'Bin Xu'}, 
    {id: 22, label: 'Bogdan A Jalba'}, 
    {id: 23, label: 'Bogdan Chicos'}, 
    {id: 24, label: 'Bostanabad Saeed Zaker'}, 
    {id: 25, label: 'Boughrine Nawal'}, 
    {id: 26, label: 'Bouzarisaravani Zahra'}, 
    {id: 27, label: 'C S Jalba'}, 
    {id: 28, label: 'Chen Dan'}, 
    {id: 29, label: 'Chen Weimiao'}, 
    {id: 30, label: 'Cheng Fu'}, 
    {id: 31, label: 'Cheng Tian'}, 
    {id: 32, label: 'Chhunthang Thanpari'}, 
    {id: 33, label: 'Chie Ishikawa'}, 
    {id: 34, label: 'Chihiro Sasakawa'}, 
    {id: 35, label: 'Chrisanthy Vlachaki'}, 
    {id: 36, label: 'Christian Stratowa'}, 
    {id: 37, label: 'Christine Lorenz'}, 
    {id: 38, label: 'Dagmar Hengge'}, 
    {id: 39, label: 'Dan Meng'}, 
    {id: 40, label: "Daniele D'Ambrosio"}, 
    {id: 41, label: 'David E Anderson'}, 
    {id: 42, label: 'Dechun Zhang'}, 
    {id: 43, label: 'Dennis Ndolo'}, 
    {id: 44, label: 'Dhiraj Valjibhai Chawda'}, 
    {id: 45, label: 'Dong Hwa Kim'}, 
    {id: 46, label: 'Dragos Catalin Jianu'}, 
    {id: 47, label: 'E A Dosumu'}, 
    {id: 48, label: 'E Stefan'}, 
    {id: 49, label: 'Edward Awh'}, 
    {id: 50, label: 'Edward K Vogel'}, 
    {id: 51, label: 'Er-Rami Mohammed'}, 
    {id: 52, label: 'Eriko Takeshima'}, 
    {id: 53, label: 'Eriko Uema'}, 
    {id: 54, label: 'Esmaeili Akbar'}, 
    {id: 55, label: 'F Gherghina'}, 
    {id: 56, label: 'Farshadfar Mohsen'}, 
    {id: 57, label: 'Fazil Hasan'}, 
    {id: 58, label: 'Feng Shuowen'}, 
    {id: 59, label: 'Fici Silvio'}, 
    {id: 60, label: 'Fu-Ji Chen'}, 
    {id: 61, label: 'Fukunori Kinjo'}, 
    {id: 62, label: 'G Miu'}, 
    {id: 63, label: 'Gaigi Siala Soumaya'}, 
    {id: 64, label: 'Garshasbi Shima'}, 
    {id: 65, label: 'Gary Ringham'}, 
    {id: 66, label: 'George Dimosthenis Tsitsas'}, 
    {id: 67, label: 'Geran Afsaneh'}, 
    {id: 68, label: 'Ghezeljehmeidan Leila Joudi'}, 
    {id: 69, label: 'Guangmei Tian'}, 
    {id: 70, label: 'H Bahadur'}, 
    {id: 71, label: 'H Michael Frisch'}, 
    {id: 72, label: 'Hai Peng'}, 
    {id: 73, label: 'Han Zou'}, 
    {id: 74, label: 'Hang Liu'}, 
    {id: 75, label: 'Hashjin Zohreh Sayyah'}, 
    {id: 76, label: 'Hategekimana Athanase'}, 
    {id: 77, label: 'He Cong Ying'}, 
    {id: 78, label: 'Heidi Wiehler'}, 
    {id: 79, label: 'Hind El Youss'}, 
    {id: 80, label: 'Hiromitsu Teruya'}, 
    {id: 81, label: 'Hitomi Mimuro'}, 
    {id: 82, label: 'Hongmei Wang'}, 
    {id: 83, label: 'Huang Xuan'}, 
    {id: 84, label: 'Hussein Hamarashid Sahar'},
    {id: 85, label: 'Hyun Yung Lee'}, 
    {id: 86, label: 'Hyung-Min Chung'}, 
    {id: 87, label: 'Inimioara Mihaela Cojocaru'}, 
    {id: 88, label: 'Ioanna Kotsi'}, 
    {id: 89, label: 'Iqbal Rabia'}, 
    {id: 90, label: 'Iranbakhsh Alireza'}, 
    {id: 91, label: 'J A Momoh'}, 
    {id: 92, label: 'Jaber Taheri Shakib'}, 
    {id: 93, label: 'Jae Chul Lee'}, 
    {id: 94, label: 'Jae Hoon Cho'}, 
    {id: 95, label: 'Jawad Rochdi'}, 
    {id: 96, label: 'Jayesh Baldania'}, 
    {id: 97, label: 'Jia Yaocheng'}, 
    {id: 98, label: 'Jiang Hanxiu'}, 
    {id: 99, label: 'Jiang Xiaomei'}, 
    {id: 100, label: 'Jianguo Luo'}, 
    {id: 101, label: 'Jiao Lei'}, 
    {id: 102, label: 'Jiro Fujita'}, 
    {id: 103, label: 'Joelle Kajuga'}, 
    {id: 104, label: 'John T Serences'}, 
    {id: 105, label: 'Jong II Baek'}, 
    {id: 106, label: 'Junfei Zhou'}, 
    {id: 107, label: 'Junwei Di'}, 
    {id: 108, label: 'Kacem Mahmoudi'}, 
    {id: 109, label: 'Kahsay Mawcha'}, 
    {id: 110, label: 'Kazuo Yamamoto'}, 
    {id: 111, label: 'Khalid Lahmadi'}, 
    {id: 112, label: 'Khayatnezhad Majid'}, 
    {id: 113, label: 'Koh Tomimori'}, 
    {id: 114, label: 'Kristin Stocks'}, 
    {id: 115, label: 'Kushal Doshi'}, 
    {id: 116, label: 'Kwang-Hyun Baek'}, 
    {id: 117, label: 'Kwang-Yul Cha'}, 
    {id: 118, label: 'Kyu-Bum Kwack'}, 
    {id: 119, label: 'L Butnaru'}, 
    {id: 120, label: 'Larypoor Mohaddeseh'}, 
    {id: 121, label: 'Letícia Colin Panegossi'}, 
    {id: 122, label: 'Li Haiying'}, 
    {id: 123, label: 'Li Huixing'}, 
    {id: 124, label: 'Li Jialing'}, 
    {id: 125, label: 'Li Jianzhang'}, 
    {id: 126, label: 'Li Minjiao'}, 
    {id: 127, label: 'Li Sha'}, 
    {id: 128, label: 'Li Zifa'}, 
    {id: 129, label: 'Lian An'}, 
    {id: 130, label: 'Liang Wang'}, 
    {id: 131, label: 'Libo Zhou'}, 
    {id: 132, label: 'Lihong Chen'}, 
    {id: 133, label: 'Lili Li'}, 
    {id: 134, label: 'Lin Lejing'}, 
    {id: 135, label: 'Lin Li'}, 
    {id: 136, label: 'Lina Fan'}, 
    {id: 137, label: 'Liu Yu'}, 
    {id: 138, label: 'M Cruce'}, 
    {id: 139, label: 'M Shafiq Ansari'}, 
    {id: 140, label: 'M Sreenivas'}, 
    {id: 141, label: 'M. V Pravin Charles'}, 
    {id: 142, label: 'Ma Di'}, 
    {id: 143, label: 'Ma Xin'}, 
    {id: 144, label: 'Ma Yuexiang'}, 
    {id: 145, label: 'Mahdavi Mojdeh'}, 
    {id: 146, label: 'Majd Ahmad'}, 
    {id: 147, label: 'Makram Hochlef'}, 
    {id: 148, label: 'Manoj Kumar'}, 
    {id: 149, label: 'Manole Cojocaru'}, 
    {id: 150, label: 'Mark Pitts'}, 
    {id: 151, label: 'Masachika Senba'}, 
    {id: 152, label: 'Mehregan Iraj'}, 
    {id: 153, label: 'Mehri Shahram'}, 
    {id: 154, label: 'Meng Kuanhong'}, 
    {id: 155, label: 'Miao He'}, 
    {id: 156, label: 'Milan K Kantesaria'}, 
    {id: 157, label: 'Minaeifar Abbas Amir'}, 
    {id: 158, label: 'Mohamed Hedi Hamdaoui'}, 
    {id: 159, label: 'Morabbi Heravi Hakimeh'}, 
    {id: 160, label: 'Mrabet Yassine'}, 
    {id: 161, label: 'Mukesh Kumar Shrewastwa'}, 
    {id: 162, label: 'Nadeem Ahmad'}, 
    {id: 163, label: 'Najafian Sakine'}, 
    {id: 164, label: 'Naoki Mori'}, 
    {id: 165, label: 'Naoki Yamamoto'}, 
    {id: 166, label: 'Naval Kishor Yadav'}, 
    {id: 167, label: 'Nikkhah Maryam'}, 
    {id: 168, label: 'Nimesh C Parikh'}, 
    {id: 169, label: 'Nisheet Patel'}, 
    {id: 170, label: 'Olfa Gharbi'}, 
    {id: 171, label: 'Ou Chun'}, 
    {id: 172, label: 'Pan Li'}, 
    {id: 173, label: 'Pan Xin'}, 
    {id: 174, label: 'Peng Xiaobang'}, 
    {id: 175, label: 'Peng Zhang'}, 
    {id: 176, label: 'Peter Lemark'}, 
    {id: 177, label: 'Prutha Desai'}, 
    {id: 178, label: 'Qi Yue'}, 
    {id: 179, label: 'Qian Xiaohui'}, 
    {id: 180, label: 'Rabindra Kumar Mittal'}, 
    {id: 181, label: 'Radu Tanasescu'}, 
    {id: 182, label: 'Rajesh Kumar Goit'}, 
    {id: 183, label: 'Rajesh Valjibhai Chawda'}, 
    {id: 184, label: 'Rakesh Bahadur Singh'}, 
    {id: 185, label: 'Richard B Islinger'}, 
    {id: 186, label: 'Rishit Jayesh Soni'}, 
    {id: 187, label: 'Roberto Gameiro'}, 
    {id: 188, label: 'Romas Geleziunas'}, 
    {id: 189, label: 'Romney C Anderson'}, 
    {id: 190, label: 'S Chaturvedi'}, 
    {id: 191, label: 'Salimpour Fahimeh'}, 
    {id: 192, label: 'Sami Limem'}, 
    {id: 193, label: 'Sanda Maria Deme'}, 
    {id: 194, label: 'Sandy Faulkner'}, 
    {id: 195, label: 'Sarhadi Nima'}, 
    {id: 196, label: 'Shakoor Abdul'}, 
    {id: 197, label: 'Sharifnia Fariba'}, 
    {id: 198, label: 'Shen Zhongyuan'}, 
    {id: 199, label: 'Shilpi Agrawal'}, 
    {id: 200, label: 'Shreyash P Gandhi'}, 
    {id: 201, label: 'Shu-Chen Mowang'}, 
    {id: 202, label: 'Shunjie Chua'}, 
    {id: 203, label: 'Slim ben Ahmed'}, 
    {id: 204, label: 'Sook-Hwan Lee'}, 
    {id: 205, label: 'Sotirios Baratsis'}, 
    {id: 206, label: 'Sreenivasan Srirangaraj'}, 
    {id: 207, label: 'Stavros Gourgiotis'}, 
    {id: 208, label: 'Stefania Kory Calomfirescu'}, 
    {id: 209, label: 'Sun Yanxia'}, 
    {id: 210, label: 'Sung Tae Park'}, 
    {id: 211, label: 'Sung-Won Cho'}, 
    {id: 212, label: 'Suzhen Zhang'}, 
    {id: 213, label: 'T Srinivas'}, 
    {id: 214, label: 'Taeko Okudaira'}, 
    {id: 215, label: 'Teizo Yoshimura'}, 
    {id: 216, label: 'Tereza Cristina Cardoso'}, 
    {id: 217, label: 'Thomas P Parks'}, 
    {id: 218, label: 'Tian Huailiang'}, 
    {id: 219, label: 'Timothy R Kuklo'}, 
    {id: 220, label: 'Ting Song'}, 
    {id: 221, label: 'Toshifumi Matsuyama'}, 
    {id: 222, label: 'Toshiya Hirayama'}, 
    {id: 223, label: 'Ulrich R Hengge'}, 
    {id: 224, label: 'Vishwajeet Rohil'}, 
    {id: 225, label: 'Waheed Abdul'}, 
    {id: 226, label: 'Walter Jentzen'}, 
    {id: 227, label: 'Wang Hua'}, 
    {id: 228, label: 'Wang Yingxue'}, 
    {id: 229, label: 'Wang Zelu'}, 
    {id: 230, label: 'Wei Liang'}, 
    {id: 231, label: 'Weixiong Zhang'}, 
    {id: 232, label: 'Wenxiang Yang'}, 
    {id: 233, label: 'Wu Xiaoxia'}, 
    {id: 234, label: 'Wu Xiaoyong'}, 
    {id: 235, label: 'XIngmin Xu'}, 
    {id: 236, label: 'Xia Haiou'}, 
    {id: 237, label: 'Xiao Hu'}, 
    {id: 238, label: 'Xiao Huaping'}, 
    {id: 239, label: 'Xie Bin'},
    {id: 240, label: 'Xing Wei'}, 
    {id: 241, label: 'Xu Chenheng'}, 
    {id: 242, label: 'Xu Pengyuan'}, 
    {id: 243, label: 'Xuhui Zhao'}, 
    {id: 244, label: 'Yang Peng'}, 
    {id: 245, label: 'Yang Xin'}, 
    {id: 246, label: 'Yanpeng Zhao'}, 
    {id: 247, label: 'Yao Jia'}, 
    {id: 248, label: 'Yao Xixi'}, 
    {id: 249, label: 'Yibing Yu'}, 
    {id: 250, label: 'Yin Juan'}, 
    {id: 251, label: 'Ying Wu'}, 
    {id: 252, label: 'Yogita Haribhai Kataria'}, 
    {id: 253, label: 'Yong Tang'}, 
    {id: 254, label: 'Yongliang Lin'}, 
    {id: 255, label: 'Yougqi Gao'}, 
    {id: 256, label: 'Yu Haiyan'}, 
    {id: 257, label: 'Yu Hangcheng'}, 
    {id: 258, label: 'Zeng Fang'}, 
    {id: 259, label: 'Zeng Xiancai'}, 
    {id: 260, label: 'Zhang Xinxin'}, 
    {id: 261, label: 'Zhang Zhiwei'}, 
    {id: 262, label: 'Zhangfeng Hu'}, 
    {id: 263, label: 'Zhao Hong'}, 
    {id: 264, label: 'Zhao Xu'}, 
    {id: 265, label: 'Zheng Tiesheng'}, 
    {id: 266, label: 'Zheng Zhongbiao'}, 
    {id: 267, label: 'Zhengzheng Wu'}, 
    {id: 268, label: 'Zhong Junbo'}, 
    {id: 269, label: 'Zhou Rui'}, 
    {id: 270, label: 'Zhou Yan'}, 
    {id: 271, label: 'Ziren Yan'}, 
    {id: 272, label: 'Ö Yükselmiş'}
]);

const edges = new vis.DataSet([
    {from: 1, to: 2},
    {from: 164, to: 222, weight: 4},
    {from: 165, to: 222, weight: 3},
    {from: 5, to: 164, weight: 3},
    {from: 164, to: 165, weight: 3},
    {from: 5, to: 165, weight: 3},
    {from: 5, to: 222, weight: 3},
    {from: 12, to: 197, weight: 2},
    {from: 191, to: 197, weight: 2},
    {from: 87, to: 149, weight: 2},
    {from: 23, to: 149, weight: 2},
    {from: 183, to: 252, weight: 2},
    {from: 6, to: 158, weight: 2},
    {from: 61, to: 151, weight: 2},
    {from: 80, to: 151, weight: 2},
    {from: 113, to: 164, weight: 2},
    {from: 80, to: 113, weight: 2},
    {from: 102, to: 113, weight: 2},
    {from: 151, to: 164, weight: 2},
    {from: 80, to: 164, weight: 2},
    {from: 33, to: 61, weight: 2},
    {from: 80, to: 102, weight: 2},
    {from: 33, to: 151, weight: 2},
    {from: 102, to: 151, weight: 2},
    {from: 34, to: 222, weight: 2},
    {from: 102, to: 164, weight: 2},
    {from: 33, to: 164, weight: 2},
    {from: 33, to: 113, weight: 2},
    {from: 61, to: 164, weight: 2},
    {from: 61, to: 113, weight: 2},
    {from: 34, to: 164, weight: 2},
    {from: 33, to: 102, weight: 2},
    {from: 61, to: 102, weight: 2},
    {from: 33, to: 80, weight: 2},
    {from: 113, to: 151, weight: 2},
    {from: 61, to: 80, weight: 2},
    {from: 5, to: 188, weight: 2},
    {from: 165, to: 188, weight: 2},
    {from: 188, to: 222, weight: 2},
    {from: 164, to: 188, weight: 2},
]);

const container = document.getElementById('mynetwork');
const data = { nodes: nodes, edges: edges };
const options = {};

const network = new vis.Network(container, data, options);

network.on("click", function (params) {
    if (params.nodes.length > 0) {
        alert(`Node clicked: ${params.nodes[0]}`);
    }
});
